janezd/trubar

- trubar/actions.py
- trubar/tests/test_actions.py
- trubar/tests/test_command_line.sh
Fixes #23: copy non-python files in translate.
> Translate: Copy all files, not just *.py

- README.md
- requirements.txt
- trubar/__main__.py
- trubar/actions.py
- trubar/config.py
- trubar/tests/test_actions.py
- trubar/tests/test_command_line.sh
- trubar/tests/test_config.py
- trubar/tests/test_project/config-no-prefix.yaml
- trubar/tests/test_project/newly_braced.yaml
Fixes #32.
This adds two relatively unrelated functionalities:
- changes in string types and prefixes:
- single quotes in source are replaced with double quotes and vice-versa, when the translation includes quotes
- string is changed to f-string if translation requires it
- configuration file with global options; currently auto-quote, auto-prefix, encoding
They are merged into the same PR because the former is regulated by the latter, and the latter is unittested by its ability to control the former.
> Add auto quotes and prefixes, and config file

- README.md
- trubar/actions.py
- trubar/tests/test_actions.py
Fixes #35.
Instead of relying on regular expressions, try parsing the string as f-string and convert it to f-string if this succeeds and finds any expressions inside the string.
To save time, do this only if the string contains a pair of braces, as check by simple regular expression (`\{.+\}`).
> Auto prefix: Better detection of use of f-strings in translations

- README.md
- trubar/actions.py
- trubar/config.py
- trubar/tests/test_command_line.sh
- trubar/tests/test_project/config-auto-import.yaml
Fixes #33.
Allows automatically adding a line at the top of the file, e.g. 
```
from Orange.widgets.utils.localization import plsi, plsi_sz  # pylint: disable=wrong-import-order
```
> Add auto import

- trubar/actions.py
- trubar/config.py
- trubar/tests/test_actions.py
- trubar/tests/test_config.py
Trubar excluded `.*tests/test_.*`. This is now configurable via config file.
> Config: Add option exclude-pattern

- trubar/actions.py
- trubar/tests/test_actions.py
Fixes #45.
If translation includes something that looks like f-string, but the original already included braces, don't add the f-prefix.
> Don't add f-prefix if braces were already there

- trubar/jaml.py
- trubar/tests/test_jaml.py
Fix an error in jaml.dump: If strings are not quoted, backslashes mustn't be escaped
> Don't escape backslashes in unquoted strings

- trubar/jaml.py
- trubar/tests/test_jaml.py
Strings with leading or trailing spaces were not quoted. This would work in principle, but raise warnings from git, and could be disturbed by editors.
> jaml.dump: use quotes for strings with leading/trailing spaces

- trubar/jaml.py
- trubar/tests/test_jaml.py
Quoted strings are parsed by `ast.literal_eval` that can trigger syntax errors. Now they are properly caught and reported.
> Jaml: Catch syntax errors in quoted strings

- pylintrc
- trubar/jaml.py
- trubar/tests/test_jaml.py
Fixes #57.
Backslashes no longer have any special meaning; reading no longer uses `ast.literal_eval`.
- In keys, any quotes within the string that match the outer quote are doubled (instead of escaped). This will be uncommon, and even when it happens, translator does not care.
- In quoted translations, the leading and trailing quote are stripped.  Inside can contain quotes of any kind and whatever else.
> Jaml: Simplify quoting

- trubar/jaml.py
- trubar/tests/test_jaml.py
Add tests for block values + minor change in parsing: `strip("\n")` is replaced by `[:-1]`, which should be the same, but the latter is closer to the actual intention - removing the trailing `\n` that was "needlessly" added.
> Test for block values, and minor change

- docs/message-files.md
- trubar/__main__.py
- trubar/jaml.py
- trubar/tests/test_jaml.py
- trubar/tests/test_messages.py
This makes messages much easier to read and less ambiguous wrt white space at the beginning.
At the same time, parser and dumper are way simpler and thus safer.
No backward compatibility. Still, it took me five minutes to adapt the entire collection of messages for Orange.
> Jaml: Remove yaml-style pipe blocks in favour of multiline strings

- trubar/actions.py
- trubar/tests/test_actions.py
Trubar didn't work on Windows because keys had backslashes instead of slashes. 😳
> Convert Windows backslashes to forward slashes in keys

- pylintrc
- trubar/__main__.py
- trubar/actions.py
- trubar/tests/shell_tests/collect/test.sh
- trubar/tests/shell_tests/translate/test.sh
- trubar/tests/test_actions.py
- trubar/tests/test_utils.py
- trubar/utils.py
Fixes #72.
Also: `-s` is now required argument for `collect` and `translate`.
> Requires -s; check for matches, recommend different dir if there are none

- trubar/__main__.py
- trubar/tests/shell_tests/merge/test.sh
Errors were reported when also written to a file. They'd have to be reported when *not* written.
Tests had another, unrelated bug.
> Merge: Fix unused reporting and tests

- trubar/__main__.py
- trubar/tests/shell_tests/_config/.trubarconfig.yaml
- trubar/tests/shell_tests/_config/test.sh
- trubar/tests/test_main.py
Fixes #73.
Default config file used to be trubar-config.yaml. It still is, but now it can also be .trubarconfig.yaml, and it has precedence.
Also, if there is no config file in the existing directory, it is loaded from source path (for `translate` and `collect`, which have `-s` option).
> Load config from .trubarconfig and from source path

- trubar/actions.py
`collect` shouldn't include files without messages. Also because jaml cannot represent them, therefore creating an invalid file.
> Collect: do not add files without messages to translation files

- docs/command-line.md
- trubar/__main__.py
- trubar/actions.py
- trubar/tests/shell_tests/collect/test.sh
- trubar/tests/test_actions.py
- trubar/tests/test_utils.py
- trubar/utils.py
Fixes #88.
Collect now
- always writes a files with removed messages,
- no longer prints out warnings about removed messages.
> Collect: Always store unused translations

- docs/command-line.md
- pylintrc
- trubar/__main__.py
- trubar/actions.py
- trubar/tests/shell_tests/collect/exp/merged_messages_newer.yaml
- trubar/tests/shell_tests/collect/exp/removed_newer.yaml
- trubar/tests/shell_tests/collect/test.sh
- trubar/tests/test_messages.py
`collect` for a large project may be slow although there are usually only a few files are modified and need to be checked.
With the new option `--newer` (`-u`), trubar compares timestamps before collecting messages from the file.
> Collect: add option --newer

- .github/workflows/test.yml
- trubar/jaml.py
- trubar/tests/test_jaml.py
- trubar/tests/test_messages.py
- Add tests on Python 3.11 and 3.12
- Fix a crash when reading jaml empty files and writing empty strings to jaml
- Remove a pylint disable that is now redundant
> Minor fixes in jaml and tests

- docs/configuration.md
- trubar/config.py
So that the conf file can be reliably read on computers with different locales
> Set default locale to utf-8

- CHANGELOG.md
- pylintrc
- setup.cfg
- trubar/actions.py
- trubar/config.py
- trubar/tests/shell_tests/translate/exp/multilingual/__init__.py
- trubar/tests/test_actions.py
Trubar puts auto imports before the docstring. This string is then no longer recognized as a docstring and will not be executed by docstring tests.
This PR checks for existence of a docstring and puts auto import after it (unless there are imports from future, which always come after the doc string).
In
```python
def f():
x = 5
def g():
return f'foo {x}'
return g()
```
The return statement is replaced with (essentially)
```python
return eval(compile(m[0, 'foo {x}'], "<string>", "eval"))
```
where `m[0]` is `"f'foo {x}'"`. This fails because `x` does not appear in `eval`'s locals.
This PR fixes it by giving the original f-string as the second index:
```python
return eval(compile(m[0, f'foo {x}'], "<string>", "eval"))
```
> Fixes for multilingual mode

- docs/configuration.md
- trubar/actions.py
- trubar/tests/shell_tests/translate/exp/multilingual/i18n/English.json
- trubar/tests/shell_tests/translate/exp/multilingual/i18n/Foolanguage.json
- trubar/tests/shell_tests/translate/exp/multilingual/i18n/Slovenian.json
- trubar/tests/shell_tests/translate/multilingual/si/translations.jaml
- trubar/tests/test_actions.py
Fixes #98.
- Do not enforce quote types because they don't matter. Let Python choose them: just call `repr` to "uneval" a string
- Don't use f-strings for translations where not necessary.
- Do not unescape raw string where originals are not raw.
> Multilingual: let Python choose quote types; don't use f-strings for translations where not necessary
